### ISSUE TITLE
Change style from 'normal' to different styles

### ISSUE THREAD

**Issue by LushawnDev** [RostiMelk/pt-string#1]
Hey, love the library - thanks for your work!

I'm wondering, is it possible to change the style from `'normal'` to something else like `'h2'`? Here's my code, I've tried adding `styles` to the options the same as the `decorators` option, but looking at the code, it looks like the styles are fixed to normal? Would it be possible to also pass the styles along like below?

If this is already possible, my bad! Please point out if I'm missing something.

```
import React from 'react'
import {defineType, defineArrayMember} from 'sanity'

const HighlightIcon = () => <span style={{fontWeight: 'bold', color: '#246D49'}}>H</span>

const HighlightDecorator = (props: any) => (
  <span style={{backgroundColor: '#246D49', padding: '2px 4px 2px 4px'}}>{props.children}</span>
)

export const heading = defineType({
  name: 'heading',
  type: 'pt-string',
  options: {
    styles: [{title: 'Heading 2', value: 'h2'}],
    decorators: [
      {
        title: 'Highlight',
        value: 'highlight',
        icon: HighlightIcon,
        component: HighlightDecorator,
      },
    ],
  },
})
```

Thanks for your work.

**Comment by RostiMelk** [comment]
Hi, thank you!

I think you are confusing styles with blocks here.

The idea of the library isn't to let the user create multiple lines of blocks, but a single one. 
If you need you need an H2, you simply output an H2 tag in your frontend with your content. 

Here is a React example:
```tsx
import {PortableText} from '@portabletext/react'

const components = {
  block: {
    normal: ({ children }) => <h2>{children}</h2>,
  }
}

const SingleLinePortableText = (props) => {
  return <PortableText value={props.value} components={components} />
}
```

**Comment by LushawnDev** [comment]
Hey thanks for the reply. You're so right, I think I was being dumb... I managed to just implement that via my frontend. Thanks again!
